### ISSUE TITLE
Look into WikiGenomes as a "web based gene annotation program to help hack the horse genome"

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UMN-EGGL/HorseGeneAnnotation#18]
I see that your "web based gene annotation program to help hack the horse genome" is currently listed as "coming soon!", so I would like to suggest that you take a look at [WikiGenomes](http://wikigenomes.org/).

It is a tool for genome annotation that combines a "web based gene annotation program" (aka [wikigenomes_base](https://github.com/SuLab/wikigenomes_base)) with [Wikidata](https://wikidata.org/) as the backend (including editing via OAuth). Sample entry: [Listeria monocytogenes EGD-e (NCBI TaxID: 169963)](http://wikigenomes.org/organism/169963/).

As far as I can tell, it has so far only been used for microbial genes, so some development work would still be needed to handle vertebrate genomes, but many of the pieces you need are there already.

One [fork](https://github.com/SuLab/ChlamBase.org) of it &mdash; [Chlambase](https://chlambase.org/) &mdash; has also been customized further for genomes from the genus *Chlamydia*. Sample entry: [Chlamydia trachomatis D/UW-3/CX (NCBI TaxID: 272561)](https://chlambase.org/organism/272561/).

All of this is overseen by the Gene Wiki team, who can be reached both [on GitHub](https://github.com/SuLab/GeneWikiCentral) and [on Wikidata](https://www.wikidata.org/wiki/Wikidata:WikiProject_Gene_Wiki) and who maintain a [list of SPARQL queries](https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples) that allow to explore the corpus of genetic and related information that is available through Wikidata, which includes the human, mouse and rat genomes.

**Comment by schae234** [comment]
Hey @Daniel-Mietchen thanks for the info! This will be useful, the WikiGenomes website has a interface close to what we were looking to design. However, I think the way we are defining "annotation" is different than the way WikiGenomes and Chlambase do. Looks like they are assigning functional labels as annotations to genes, where we are still trying to define the structure of genes. So I guess in a sense we are more trying to annotate the genome rather than the individual genes. We have some [documentation on this steps already](https://github.com/UMN-EGGL/HorseGeneAnnotation/blob/master/_pages/What_is_Gene_Annotation.md) but its good feedback for us because we want our objectives to be clear. 

The github repos you linked will be really useful for how they organized and stored their gene features.
